language: python
branches:
  only: 
    - master
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to install dependencies
install: 
  - pip install -r py-requirements/dev.txt
  - nvm install 6
  - npm install
  - npm run prod
# command to run tests
script:
  - npm run analyze
